#!/usr/bin/env bash

# Install Nginx web server
sudo apt-get update
sudo apt-get install -y nginx

# Create custom 404 error page
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html

# Configure Nginx to use custom 404 page
sudo sed -i "s|#error_page 404 /404.html;|error_page 404 /404.html;|" /etc/nginx/sites-enabled/default
sudo sed -i "s|#location = /404.html {|location = /404.html {|" /etc/nginx/sites-enabled/default
sudo sed -i "s|#}#end of error_page|}#end of error_page|" /etc/nginx/sites-enabled/default

# Restart Nginx service to apply changes
sudo service restart nginx
