#!/usr/bin/env bash
# Create a script to install and configure HAProxy on lb-01 (loadbalancer) server using roundrobbin algorithm

# Installs, configures, and starts the load balancer
sudo apt-get update
sudo apt-get -y install haproxy

# the load balancer's configuration
DOMAIN_NAME='www.weblegend.tech'

server_config=\
"
backend $DOMAIN_NAME-backend
        balance roundrobin
        server 176087-web-01 34.232.52.184 check
        server 176087-web-02 35.153.19.183 check
frontend $DOMAIN_NAME-frontend
        bind *:80
        mode http
        default_backend $DOMAIN_NAME-backend
"

echo "$server_config" | sudo tee -a /etc/haproxy/haproxy.cfg

# enable haproxy to be started by init script
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

sudo service haproxy restart
