#!/usr/bin/env bash
# Create a script to install and configure HAProxy on lb-01 (loadbalancer) server using roundrobbin algorithm

#!/usr/bin/env bash
# Installs, configures, and starts the load balancer
sudo apt-get update
sudo apt-get -y install --no-install-recommends software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.4
sudo apt-get -y install haproxy

# the load balancer's configuration
DOMAIN_NAME='divinelewis.tech'

HAPROXY_LB_CONFIG=\
"
#--$DOMAIN_NAME-params-begin--
backend $DOMAIN_NAME-backend
        balance roundrobin
        server 173867-web-01 52.91.145.188 check
        server 173867-web-02 100.25.137.235 check
frontend $DOMAIN_NAME-frontend
        bind *:80
        mode http
        default_backend $DOMAIN_NAME-backend
#--$DOMAIN_NAME-params-end--
"

echo "$server_config" | sudo dd status=none of=/etc/haproxy/haproxy.cfg

# enable haproxy to be started by init script
echo "ENABLED=1" | sudo dd status=none of=/etc/default/haproxy

if [ "$(pgrep -c haproxy)" -le 0 ]; then
        sudo service haproxy start
else
        sudo service haproxy restart
fi
